### ISSUE TITLE
Mod loader broke due to update

### ISSUE THREAD

**Issue by YousifAlkhalaf** [blueskythlikesclouds/RainbowModLoader#1]
It seems that the mod loader has broken with Sonic Colors Ultimate's newest update. Do you know how to fix this?
![Screenshot 2021-12-26 074224](https://user-images.githubusercontent.com/58121901/147413139-3d563491-9792-4503-ae2a-9c93b3837b51.png)

**Comment by blueskythlikesclouds** [comment]
I have to add support for it. I'll do it when I have the chance.

**Comment by YousifAlkhalaf** [comment]
Thank you very much.

**Comment by blueskythlikesclouds** [comment]
Fixed as of d348066.
