### ISSUE TITLE
[Steam Deck] Lighting mods crashing on startup

### ISSUE THREAD

**Issue by amso71** [blueskythlikesclouds/RainbowModLoader#2]
colors ultimate is always crashing on the first loading screen before the title when it tries to load a lighting mod, and i have no idea why. gens and frontiers work just fine with lighting mods, though i haven’t tried with lost world or forces.
what’s odd is that stuff like loco’s reimagined lighting or environment tweaks will crash on the aforementioned loading screen, while others like enhanced lighting will only crash on certain levels.

**Comment by blueskythlikesclouds** [comment]
Not sure how I could help you with this considering I don't have a Steam Deck.

**Comment by amso71** [comment]
Well it’s likely not a RML issue under further investigation as loading mods through the built in acorn mod loader encounters the same issue, so this is something related to steam proton

**Comment by amso71** [comment]
i’ve been tinkering with this and i added some overrides to the proton prefix that allowed lighting mods to run, so i’ll close this

**Comment by blueskythlikesclouds** [comment]
Would be cool if you mentioned them so other people who run into this issue could use something for reference.

**Comment by amso71** [comment]
- install protontricks to your steam deck via the discover app
- open protontricks and click the sonic colors: ultimate prefix
- go to “install a dll or component”
- select d3dcompiler_47 and install
- now go to “run winecfg”
- add kerberos and msv0_1 as overrides
- i believe d3dcompiler is an override by default, but if it’s not, add it
it should run correctly now, if it doesn’t, reopen winecfg and set the overrides you just added as native (windows) by clicking on them and pressing edit
